import { db } from "@/db";
import { orderItems, orders, recipes } from "@/db/schema";
import { longDate, money, numberValue } from "@/lib/format";
import { eq } from "drizzle-orm";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, MessageCircle, Sparkles } from "lucide-react";
import PrintButton from "@/components/PrintButton";
export default async function PedidoDetalhePage({ params }: { params: Promise<{ id: string }> }) {
 const { id } = await params; const orderId=Number(id); const order=await db.query.orders.findFirst({where:eq(orders.id,orderId)}); if(!order) notFound();
 const items=await db.select({quantity:orderItems.quantity, unitPrice:orderItems.unitPrice, recipeName:recipes.name}).from(orderItems).innerJoin(recipes,eq(orderItems.recipeId,recipes.id)).where(eq(orderItems.orderId,orderId));
 const phone=order.customerPhone?.replace(/\D/g,"")||""; const message=encodeURIComponent(`Olá ${order.customerName}! Segue o orçamento da Doces Gourmet da Ana:\n\n${items.map(i=>`• ${i.quantity}x ${i.recipeName}: ${money(numberValue(i.unitPrice)*i.quantity)}`).join("\n")}\n\nTotal: ${money(order.totalAmount)}\nData combinada: ${longDate(order.deliveryDate)}\n\nQualquer ajuste é só me chamar.`);
 return <div className="mx-auto max-w-4xl space-y-6"><div className="flex flex-col gap-3 print:hidden md:flex-row md:items-center md:justify-between"><Link href="/pedidos" className="inline-flex items-center text-sm font-black text-slate-500 hover:text-rose-600"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar</Link><div className="flex gap-2"><PrintButton />{phone&&<a href={`https://wa.me/55${phone}?text=${message}`} target="_blank" className="inline-flex items-center rounded-2xl bg-emerald-500 px-4 py-3 text-sm font-black text-white shadow-sm"><MessageCircle className="mr-2 h-4 w-4"/>WhatsApp</a>}</div></div><section className="rounded-[2rem] bg-white p-8 shadow-sm print:shadow-none"><div className="mb-8 flex items-start justify-between border-b border-slate-100 pb-6"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-rose-50 px-3 py-1 text-xs font-black uppercase tracking-widest text-rose-500"><Sparkles className="h-3.5 w-3.5"/>Doces Gourmet da Ana</div><h1 className="text-3xl font-black text-slate-950">Orçamento #{String(order.id).padStart(4,"0")}</h1><p className="mt-2 text-slate-500">Encomenda para {longDate(order.deliveryDate)}</p></div><div className="text-right"><p className="text-xs font-black uppercase tracking-widest text-slate-400">Total</p><p className="text-3xl font-black text-rose-600">{money(order.totalAmount)}</p></div></div><div className="mb-8 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-slate-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-slate-400">Cliente</p><p className="mt-2 text-xl font-black">{order.customerName}</p><p className="text-slate-500">{order.customerPhone||"Sem telefone"}</p></div><div className="rounded-3xl bg-slate-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-slate-400">Status</p><p className="mt-2 text-xl font-black capitalize">{order.status}</p></div></div><table className="w-full text-left"><thead className="text-xs font-black uppercase tracking-widest text-slate-400"><tr className="border-b border-slate-100"><th className="py-3">Produto</th><th className="text-center">Qtd</th><th className="text-right">Unitário</th><th className="text-right">Subtotal</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item,index)=><tr key={index}><td className="py-4 font-black">{item.recipeName}</td><td className="text-center">{item.quantity}</td><td className="text-right">{money(item.unitPrice)}</td><td className="text-right font-black text-rose-600">{money(numberValue(item.unitPrice)*item.quantity)}</td></tr>)}</tbody></table>{order.notes&&<div className="mt-8 rounded-3xl bg-rose-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-rose-400">Observações</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{order.notes}</p></div>}</section></div>;
}
