import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { CalendarDays, ChefHat, ClipboardList, Home, Package, Sparkles, WalletCards } from "lucide-react";
import MobileNav from "@/components/MobileNav";
import "./globals.css";
export const metadata: Metadata = { title: "Doces Gourmet da Ana", description: "Sistema de encomendas, receitas, estoque e financeiro." };
const menuItems = [
  { name: "Dashboard", href: "/", icon: Home, iconName: "Home" }, { name: "Pedidos", href: "/pedidos", icon: ClipboardList, iconName: "ClipboardList" }, { name: "Receitas", href: "/receitas", icon: ChefHat, iconName: "ChefHat" }, { name: "Ingredientes", href: "/ingredientes", icon: Package, iconName: "Package" }, { name: "Estoque", href: "/estoque", icon: CalendarDays, iconName: "CalendarDays" }, { name: "Financeiro", href: "/financeiro", icon: WalletCards, iconName: "WalletCards" },
];
export default function RootLayout({ children }: { children: ReactNode }) {
  return <html lang="pt-br"><body className="bg-[#fbf8f6] text-slate-900 antialiased"><div className="flex min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,#ffe4ef,transparent_28%),linear-gradient(180deg,#fff,#fbf8f6)]"><aside className="hidden w-72 shrink-0 border-r border-rose-100/70 bg-white/80 backdrop-blur-xl md:flex md:flex-col"><div className="p-7"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-3xl bg-rose-50 text-rose-500 ring-1 ring-rose-100"><Sparkles className="h-6 w-6" /></div><div><h1 className="text-lg font-black tracking-tight text-slate-950">Doces Gourmet</h1><p className="text-xs font-medium text-slate-400">da Ana</p></div></div></div><nav className="flex-1 space-y-1 px-4">{menuItems.map((item) => <Link key={item.name} href={item.href} className="group flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold text-slate-500 transition hover:bg-rose-50 hover:text-rose-600"><item.icon className="h-5 w-5" />{item.name}</Link>)}</nav><div className="m-4 rounded-3xl border border-rose-100 bg-rose-50/70 p-4"><p className="text-sm font-black text-slate-900">Painel inteligente</p><p className="mt-2 text-xs leading-5 text-slate-500">Controle encomendas, custos e estoque sem planilha paralela.</p></div></aside><div className="flex min-w-0 flex-1 flex-col"><MobileNav menuItems={menuItems.map(({ name, href, iconName }) => ({ name, href, iconName }))} /><main className="flex-1 overflow-auto p-4 md:p-8"><div className="mx-auto max-w-7xl">{children}</div></main></div></div></body></html>;
}
